const data = {
  success: true,
  user: {
    user: { username: "core", profile_pic: null },
    potential_win: 400,
    odds: 276,
    odds_won: 7.26,
    number_of_wins: 4,
    played: 10,
    forecasts: [
      {
        id: 231,
        fixture: {
          home_team: "Arsenal",
          home_team_crest: "/media/images/19.png",
          home_goals: 2,
          away_team: "Fulham",
          away_team_crest: "/media/images/11.png",
          away_goals: 2,
          competition: "Premier League",
          date: "2023-08-26 15:00:00",
          has_started: true,
          open: false,
        },
        forecast: "HOME",
        code: 31,
      },
      {
        id: 232,
        fixture: {
          home_team: "Arsenal",
          home_team_crest: "/media/images/19.png",
          home_goals: 2,
          away_team: "Fulham",
          away_team_crest: "/media/images/11.png",
          away_goals: 2,
          competition: "Premier League",
          date: "2023-08-26 15:00:00",
          has_started: true,
          open: false,
        },
        forecast: "NG",
        code: 31,
      },
      {
        id: 233,
        fixture: {
          home_team: "Arsenal",
          home_team_crest: "/media/images/19.png",
          home_goals: 2,
          away_team: "Fulham",
          away_team_crest: "/media/images/11.png",
          away_goals: 2,
          competition: "Premier League",
          date: "2023-08-26 15:00:00",
          has_started: true,
          open: false,
        },
        forecast: "OVER2.5",
        code: 31,
      },
      {
        id: 234,
        fixture: {
          home_team: "Arsenal",
          home_team_crest: "/media/images/19.png",
          home_goals: 2,
          away_team: "Fulham",
          away_team_crest: "/media/images/11.png",
          away_goals: 2,
          competition: "Premier League",
          date: "2023-08-26 15:00:00",
          has_started: true,
          open: false,
        },
        forecast: "H2NG",
        code: 31,
      },
      {
        id: 235,
        fixture: {
          home_team: "Villarreal",
          home_team_crest: "/media/images/3477.png",
          home_goals: 3,
          away_team: "FC Barcelona",
          away_team_crest: "/media/images/83.png",
          away_goals: 4,
          competition: "La Liga",
          date: "2023-08-27 16:30:00",
          has_started: true,
          open: false,
        },
        forecast: "AWAY",
        code: 31,
      },
      {
        id: 236,
        fixture: {
          home_team: "Villarreal",
          home_team_crest: "/media/images/3477.png",
          home_goals: 3,
          away_team: "FC Barcelona",
          away_team_crest: "/media/images/83.png",
          away_goals: 4,
          competition: "La Liga",
          date: "2023-08-27 16:30:00",
          has_started: true,
          open: false,
        },
        forecast: "OVER2.5",
        code: 31,
      },
      {
        id: 237,
        fixture: {
          home_team: "Villarreal",
          home_team_crest: "/media/images/3477.png",
          home_goals: 3,
          away_team: "FC Barcelona",
          away_team_crest: "/media/images/83.png",
          away_goals: 4,
          competition: "La Liga",
          date: "2023-08-27 16:30:00",
          has_started: true,
          open: false,
        },
        forecast: "GG",
        code: 31,
      },
      {
        id: 238,
        fixture: {
          home_team: "Paris Saint Germain",
          home_team_crest: "/media/images/591.png",
          home_goals: 3,
          away_team: "Lens",
          away_team_crest: "/media/images/271.png",
          away_goals: 1,
          competition: "Ligue 1",
          date: "2023-08-26 20:00:00",
          has_started: true,
          open: false,
        },
        forecast: "UNDER2.5",
        code: 31,
      },
      {
        id: 239,
        fixture: {
          home_team: "Paris Saint Germain",
          home_team_crest: "/media/images/591.png",
          home_goals: 3,
          away_team: "Lens",
          away_team_crest: "/media/images/271.png",
          away_goals: 1,
          competition: "Ligue 1",
          date: "2023-08-26 20:00:00",
          has_started: true,
          open: false,
        },
        forecast: "H1GG",
        code: 31,
      },
      {
        id: 240,
        fixture: {
          home_team: "Frosinone",
          home_team_crest: "/media/images/4070.png",
          home_goals: 2,
          away_team: "Atalanta",
          away_team_crest: "/media/images/708.png",
          away_goals: 1,
          competition: "Serie A",
          date: "2023-08-26 17:30:00",
          has_started: true,
          open: false,
        },
        forecast: "AWAY",
        code: 31,
      },
    ],
  },
  opponent: {
    user: { username: "bolly", profile_pic: null },
    potential_win: 400,
    odds: 42755,
    odds_won: 32.76,
    number_of_wins: 5,
    played: 9,
    forecasts: [
      {
        id: 271,
        fixture: {
          home_team: "Sheffield United",
          home_team_crest: "/media/images/21.png",
          home_goals: 1,
          away_team: "Manchester City",
          away_team_crest: "/media/images/9_cnp3CcU.png",
          away_goals: 2,
          competition: "Premier League",
          date: "2023-08-27 14:00:00",
          has_started: true,
          open: false,
        },
        forecast: "HOME",
        code: 35,
      },
      {
        id: 272,
        fixture: {
          home_team: "Sheffield United",
          home_team_crest: "/media/images/21.png",
          home_goals: 1,
          away_team: "Manchester City",
          away_team_crest: "/media/images/9_cnp3CcU.png",
          away_goals: 2,
          competition: "Premier League",
          date: "2023-08-27 14:00:00",
          has_started: true,
          open: false,
        },
        forecast: "OVER2.5",
        code: 35,
      },
      {
        id: 273,
        fixture: {
          home_team: "Sheffield United",
          home_team_crest: "/media/images/21.png",
          home_goals: 1,
          away_team: "Manchester City",
          away_team_crest: "/media/images/9_cnp3CcU.png",
          away_goals: 2,
          competition: "Premier League",
          date: "2023-08-27 14:00:00",
          has_started: true,
          open: false,
        },
        forecast: "GG",
        code: 35,
      },
      {
        id: 274,
        fixture: {
          home_team: "Sheffield United",
          home_team_crest: "/media/images/21.png",
          home_goals: 1,
          away_team: "Manchester City",
          away_team_crest: "/media/images/9_cnp3CcU.png",
          away_goals: 2,
          competition: "Premier League",
          date: "2023-08-27 14:00:00",
          has_started: true,
          open: false,
        },
        forecast: "H1GG",
        code: 35,
      },
      {
        id: 275,
        fixture: {
          home_team: "Sheffield United",
          home_team_crest: "/media/images/21.png",
          home_goals: 1,
          away_team: "Manchester City",
          away_team_crest: "/media/images/9_cnp3CcU.png",
          away_goals: 2,
          competition: "Premier League",
          date: "2023-08-27 14:00:00",
          has_started: true,
          open: false,
        },
        forecast: "H2GG",
        code: 35,
      },
      {
        id: 276,
        fixture: {
          home_team: "Newcastle United",
          home_team_crest: "/media/images/20.png",
          home_goals: 1,
          away_team: "Liverpool",
          away_team_crest: "/media/images/8_jXaDK6P.png",
          away_goals: 2,
          competition: "Premier League",
          date: "2023-08-27 16:30:00",
          has_started: true,
          open: false,
        },
        forecast: "HOME",
        code: 35,
      },
      {
        id: 277,
        fixture: {
          home_team: "Newcastle United",
          home_team_crest: "/media/images/20.png",
          home_goals: 1,
          away_team: "Liverpool",
          away_team_crest: "/media/images/8_jXaDK6P.png",
          away_goals: 2,
          competition: "Premier League",
          date: "2023-08-27 16:30:00",
          has_started: true,
          open: false,
        },
        forecast: "OVER2.5",
        code: 35,
      },
      {
        id: 278,
        fixture: {
          home_team: "Newcastle United",
          home_team_crest: "/media/images/20.png",
          home_goals: 1,
          away_team: "Liverpool",
          away_team_crest: "/media/images/8_jXaDK6P.png",
          away_goals: 2,
          competition: "Premier League",
          date: "2023-08-27 16:30:00",
          has_started: true,
          open: false,
        },
        forecast: "GG",
        code: 35,
      },
      {
        id: 279,
        fixture: {
          home_team: "Newcastle United",
          home_team_crest: "/media/images/20.png",
          home_goals: 1,
          away_team: "Liverpool",
          away_team_crest: "/media/images/8_jXaDK6P.png",
          away_goals: 2,
          competition: "Premier League",
          date: "2023-08-27 16:30:00",
          has_started: true,
          open: false,
        },
        forecast: "H1GG",
        code: 35,
      },
      {
        id: 280,
        fixture: {
          home_team: "Luton Town",
          home_team_crest: "/media/images/115.png",
          home_goals: 0,
          away_team: "West Ham United",
          away_team_crest: "/media/images/1.png",
          away_goals: 0,
          competition: "Premier League",
          date: "2023-09-01 20:00:00",
          has_started: false,
          open: true,
        },
        forecast: "OVER2.5",
        code: 35,
      },
    ],
  },
};
